# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffo < Formula
  desc "Scaffolding tool for Go projects"
  homepage "https://github.com/razpinator/scaffo"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/razpinator/scaffo/releases/download/v0.0.4/scaffo_Darwin_x86_64.tar.gz"
      sha256 "875c0722111177dde23cfb141190606667255ef2f3234768b9bd325ffc6b0b17"

      def install
        bin.install "scaffo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/razpinator/scaffo/releases/download/v0.0.4/scaffo_Darwin_arm64.tar.gz"
      sha256 "6a28771bad13f40cd00c5b49b744ac434b93dca512e23bb0aa355f3516c6c15c"

      def install
        bin.install "scaffo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/razpinator/scaffo/releases/download/v0.0.4/scaffo_Linux_x86_64.tar.gz"
      sha256 "02fe1f994659bfd3f676d0df16ca0dc3baa40bf75a51e4858b9422c5999c9ced"
      def install
        bin.install "scaffo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/razpinator/scaffo/releases/download/v0.0.4/scaffo_Linux_arm64.tar.gz"
      sha256 "24562acce7e69ebced5dc8e37ea4b0da61ec10cddcbb2cd35ddad7516eae9193"
      def install
        bin.install "scaffo"
      end
    end
  end

  test do
    system "#{bin}/scaffo --version"
  end
end
