# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scaffo < Formula
  desc "Scaffolding tool for Go projects"
  homepage "https://github.com/razpinator/scaffo"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/razpinator/scaffo/releases/download/v0.0.5/scaffo_Darwin_x86_64.tar.gz"
      sha256 "578e53c0a8c4839628d873ac06abeb835b144b78e14f66be6251f49f0118a430"

      def install
        bin.install "scaffo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/razpinator/scaffo/releases/download/v0.0.5/scaffo_Darwin_arm64.tar.gz"
      sha256 "993f29719dc7500ddb34085fcf7b177532573c6343f9c854391543efe3d7149d"

      def install
        bin.install "scaffo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/razpinator/scaffo/releases/download/v0.0.5/scaffo_Linux_x86_64.tar.gz"
      sha256 "53e95f85ceb9f0866d666806f9eba97a7e0565dd0486d8e30afd48e4d40da614"
      def install
        bin.install "scaffo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/razpinator/scaffo/releases/download/v0.0.5/scaffo_Linux_arm64.tar.gz"
      sha256 "b4ae027b4b6f27a979ddf266af9ce75db5a7e2f226cd5622042dfeae0642588e"
      def install
        bin.install "scaffo"
      end
    end
  end

  test do
    system "#{bin}/scaffo --version"
  end
end
