# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gmx < Formula
  desc "GMX CLI - A powerful code generation and management tool"
  homepage "https://github.com/razpinator/gmx"
  version "0.0.11"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/razpinator/gmx.git",
          tag:      "v0.0.11",
          revision: "HEAD"
    end
    if Hardware::CPU.intel?
      url "https://github.com/razpinator/gmx.git",
          tag:      "v0.0.11",
          revision: "HEAD"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/razpinator/gmx.git",
          tag:      "v0.0.11",
          revision: "HEAD"
    end
    if Hardware::CPU.intel?
      url "https://github.com/razpinator/gmx.git",
          tag:      "v0.0.11",
          revision: "HEAD"
    end
  end

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w"), "."
  end

  test do
    system bin/"gmx", "--version"
  end
end